[package]
name = "kmers"
version = "0.1.0"
edition = "2021"

[lib]
name = "kmers"
crate-type = ["cdylib", "rlib"]

[dependencies]
csv = "1.3.0"
pyo3 = { version = "0.22.5", features = ["extension-module"] }
rand = "0.8.5"
